import SwiftUI

struct WorkoutView: View {
    @State private var days:[WorkoutDay]=[]; @State private var error:String?; @State private var showAdd=false
    var body: some View { List { ForEach(days) { day in Section(day.label) { ForEach(Array(day.exercises.enumerated()), id:\.offset) { idx, ex in NavigationLink { ExerciseSessionView(day:day, index:idx, exercise:ex) } label:{ HStack{ Text("\(idx+1)").font(.caption.bold()).frame(width:28,height:28).background(.cyan.opacity(.15),in:Circle()); Text(ex).lineLimit(2) } }.swipeActions(edge:.trailing){ Button(role:.destructive){ Task{ try? await APIClient.shared.deleteExercise(day:day.key,name:ex); await load() } } label:{ Label("حذف",systemImage:"trash") } } } Button { showAdd=true } label:{ Label("إضافة تمرين",systemImage:"plus.circle.fill") } } } if let error { Text(error).foregroundStyle(.red) } }.navigationTitle("التمارين").toolbar{ Button{ Task{await load()} }label:{Image(systemName:"arrow.clockwise")} }.task{await load()}.sheet(isPresented:$showAdd){ AddExerciseView(days:days){ Task{await load()} } } }
    private func load() async { do{days=try await APIClient.shared.plan()}catch{self.error=error.localizedDescription} }
}
struct AddExerciseView: View { let days:[WorkoutDay]; let onDone:()->Void; @Environment(\.dismiss) var dismiss; @State var day=""; @State var name=""; var body:some View{ NavigationStack{ Form{ Picker("اليوم",selection:$day){ForEach(days){Text($0.label).tag($0.key)}}; TextField("اسم التمرين",text:$name) }.navigationTitle("إضافة تمرين").toolbar{ToolbarItem(placement:.cancellationAction){Button("إلغاء"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("حفظ"){Task{try? await APIClient.shared.addExercise(day:day.isEmpty ? days.first?.key ?? "d1":day,name:name);onDone();dismiss()}}.disabled(name.trimmingCharacters(in:.whitespaces).count<2)}} }.onAppear{if day.isEmpty{day=days.first?.key ?? "d1"}} }
}
struct ExerciseSessionView: View {
    let day:WorkoutDay; let index:Int; let exercise:String; @State private var ctx:WorkoutContext?; @State private var weight=""; @State private var reps=""; @State private var editing:GymSet?; @State private var error:String?
    var body:some View{ ScrollView{VStack(spacing:14){ Card{Text(exercise).font(.title3.bold());Text(day.label).foregroundStyle(.secondary)}; if let c=ctx{ if let r=c.recommendation?.text{Card{Label("الاقتراح القادم",systemImage:"brain.head.profile").font(.headline);Text(r).padding(.top,4)}}; HStack{TextField("الوزن",text:$weight).keyboardType(.decimalPad).textFieldStyle(.roundedBorder);TextField("العدات",text:$reps).keyboardType(.numberPad).textFieldStyle(.roundedBorder)}; Button{Task{await save()}}label:{Label("حفظ الجولة",systemImage:"checkmark.circle.fill").frame(maxWidth:.infinity).padding()}.buttonStyle(.borderedProminent).controlSize(.large); Card{Text("جولات اليوم").font(.headline); if c.todaySets.isEmpty{Text("لا توجد جولات بعد").foregroundStyle(.secondary)}else{ForEach(c.todaySets){s in HStack{Text("جولة \(s.setNumber)");Spacer();Text("\(s.weight,gSpecifier) كجم × \(s.reps)").bold();Button{editing=s}label:{Image(systemName:"pencil.circle.fill")}}.padding(.vertical,5)}}}; if let last=c.lastSession{Card{Text("آخر جلسة — \(last.date)").font(.headline);ForEach(last.sets){s in Text("جولة \(s.setNumber): \(s.weight,gSpecifier) كجم × \(s.reps)")}}} }; if let error{Text(error).foregroundStyle(.red)} }.padding()}.navigationTitle("تسجيل تمرين").navigationBarTitleDisplayMode(.inline).task{await load()}.refreshable{await load()}.sheet(item:$editing){set in EditSetView(set:set){r,w in Task{do{_ = try await APIClient.shared.editTodaySet(day:day.key,idx:index,set:set.setNumber,reps:r,weight:w);await load()}catch{self.error=error.localizedDescription}}} } }
    private func load()async{do{ctx=try await APIClient.shared.workoutContext(day:day.key,idx:index)}catch{self.error=error.localizedDescription}}
    private func save()async{guard let r=Int(reps),let w=Double(weight)else{error="تأكد من الوزن والعدات";return};do{let x=try await APIClient.shared.saveSet(day:day.key,idx:index,reps:r,weight:w);ctx=WorkoutContext(ok:true,dayLabel:day.label,exercise:exercise,todaySets:x.todaySets,lastSession:ctx?.lastSession,recommendation:ctx?.recommendation);reps=""}catch{self.error=error.localizedDescription}}
}
extension Double { var gSpecifier:String { formatted(.number.precision(.fractionLength(0...2))) } }
struct EditSetView: View { let set:GymSet; let onSave:(Int,Double)->Void; @Environment(\.dismiss)var dismiss; @State var reps="";@State var weight="";var body:some View{NavigationStack{Form{TextField("الوزن",text:$weight).keyboardType(.decimalPad);TextField("العدات",text:$reps).keyboardType(.numberPad)}.navigationTitle("تعديل الجولة").toolbar{ToolbarItem(placement:.cancellationAction){Button("إلغاء"){dismiss()}};ToolbarItem(placement:.confirmationAction){Button("حفظ"){if let r=Int(reps),let w=Double(weight){onSave(r,w);dismiss()}}}}}.onAppear{reps="\(set.reps)";weight=set.weight.gSpecifier}} }
